MDBoxLayout:
	orientation: 'vertical'
	MDScreen:
	
		MDRectangleFlatButton:
			text: 'Instalar (v1.0)'
			pos_hint: {'center_x':.5,'center_y': .6}
			#on_release: app.show_alert_dialog("Instalando. Por favor, aguarde entre 1-3 min ...")
			on_release: app.show_alert_dialog("Instalado com sucesso!")
		
		MDRectangleFlatButton:
			id: exit_button
			text: 'Sair'
			pos_hint: {'center_x':.5,'center_y': .5}
			on_release: app.stop()

